import { useEffect, useState } from "react";
import { FileText, Plus, Search, Copy, Pencil } from "lucide-react";
import Modal from "../components/Modal";
import { promptService } from "../services/promptService";
import type { Prompt } from "../types/api";

export default function Prompts(){
 const [items,setItems]=useState<Prompt[]>([]);const [selected,setSelected]=useState<Prompt|null>(null);const [search,setSearch]=useState("");const [modal,setModal]=useState(false);const [name,setName]=useState("");const [description,setDescription]=useState("");const [category,setCategory]=useState("General");const [template,setTemplate]=useState("");const [notice,setNotice]=useState("");
 async function load(){const result=await promptService.list();setItems(result);if(!selected&&result.length)setSelected(result[0]);}
 useEffect(()=>{load().catch(()=>setNotice("Unable to load prompts."));},[]);
 const filtered=items.filter(p=>`${p.name} ${p.description} ${p.category}`.toLowerCase().includes(search.toLowerCase()));
 async function save(e:React.FormEvent){e.preventDefault();try{const p=await promptService.create({name,description,category,template});setItems(await promptService.list());setSelected(p);setModal(false);setName("");setDescription("");setTemplate("");setNotice("Prompt created in demo mode.");}catch(err){setNotice(err instanceof Error?err.message:"Unable to create prompt.");}}
 return <div className="page-stack" data-testid="prompts-page">
  <div className="page-heading"><div><h1>Prompts</h1><p>Manage reusable instruction templates for your MCP workflows.</p></div><button className="button primary" onClick={()=>setModal(true)} data-testid="create-prompt-btn"><Plus size={17}/> Create Prompt</button></div>
  {notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss notice">×</button></div>}
  <div className="filter-row"><div className="search-field"><Search size={16}/><input placeholder="Search prompts..." value={search} onChange={e=>setSearch(e.target.value)} data-testid="prompt-search" aria-label="Search prompts"/></div><span className="muted">{filtered.length} prompts</span></div>
  <div className="catalog-layout prompts-layout"><section className="panel prompt-list" data-testid="prompt-list">{filtered.map(p=><button key={p.id} className={`prompt-row ${selected?.id===p.id?"selected":""}`} onClick={()=>setSelected(p)} data-testid="prompt-row" data-prompt-name={p.name}><span className="entity-icon"><FileText size={18}/></span><span className="tool-row-copy"><strong>{p.name}</strong><small>{p.description}</small></span><span className="category-chip">{p.category}</span><span className="icon-button small"><Pencil size={14}/></span></button>)}{!filtered.length&&<div className="empty-state">No prompts found.</div>}</section>
  <aside className="panel detail-panel" data-testid="prompt-details-panel"><div className="tabs"><button className="tab active">Details</button><button className="tab">Variables</button></div>{selected?<><div className="detail-title"><span className="entity-icon large"><FileText size={23}/></span><div><h2>{selected.name}</h2><span className="status-badge success">{selected.status}</span></div></div><label className="detail-field">Description<p>{selected.description}</p></label><label className="detail-field">Category<p>{selected.category}</p></label><div className="code-header"><span>Prompt template</span><button className="text-link" onClick={()=>navigator.clipboard?.writeText(selected.template)} data-testid="copy-prompt-btn"><Copy size={14}/> Copy</button></div><pre className="code-block prompt-template">{selected.template}</pre></>:<div className="empty-state">Select a prompt.</div>}</aside></div>
  {modal&&<Modal title="Create Prompt" onClose={()=>setModal(false)} testId="create-prompt-modal"><form className="form-stack" onSubmit={save} data-testid="create-prompt-form"><label>Name<input required value={name} onChange={e=>setName(e.target.value)} data-testid="prompt-name-input"/></label><label>Description<input required value={description} onChange={e=>setDescription(e.target.value)} data-testid="prompt-description-input"/></label><label>Category<select value={category} onChange={e=>setCategory(e.target.value)} data-testid="prompt-category-select"><option>General</option><option>QA</option><option>Code Review</option><option>Documentation</option></select></label><label>Template<textarea required rows={6} value={template} onChange={e=>setTemplate(e.target.value)} placeholder="Use {{variable_name}} for variables" data-testid="prompt-template-input"/></label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setModal(false)}>Cancel</button><button className="button primary" type="submit" data-testid="save-prompt-btn">Save Prompt</button></div></form></Modal>}
 </div>;
}
