import { useEffect, useState } from "react";
import { Box, Plus, Search } from "lucide-react";
import Modal from "../components/Modal";
import { serviceCatalogService } from "../services/serviceCatalogService";
import type { CatalogService } from "../types/api";

export default function Services(){
 const [items,setItems]=useState<CatalogService[]>([]);const [search,setSearch]=useState("");const [modal,setModal]=useState(false);const [name,setName]=useState("");const [kind,setKind]=useState<CatalogService["kind"]>("API");const [owner,setOwner]=useState("Platform");const [repository,setRepository]=useState("");const [environment,setEnvironment]=useState("local");const [description,setDescription]=useState("");const [notice,setNotice]=useState("");
 async function load(){setItems(await serviceCatalogService.list());}
 useEffect(()=>{load().catch(()=>setNotice("Unable to load service catalog."));},[]);
 const filtered=items.filter(i=>`${i.name} ${i.kind} ${i.owner} ${i.repository}`.toLowerCase().includes(search.toLowerCase()));
 async function save(e:React.FormEvent){e.preventDefault();try{await serviceCatalogService.create({name,kind,owner,repository,environment,description});await load();setModal(false);setName("");setRepository("");setDescription("");setNotice("Service registered in demo mode.");}catch(err){setNotice(err instanceof Error?err.message:"Unable to register service.");}}
 return <div className="page-stack" data-testid="services-page"><div className="page-heading"><div><h1>Service Catalog</h1><p>Register deployable applications and track ownership, repositories and environments.</p></div><button className="button primary" onClick={()=>setModal(true)} data-testid="add-catalog-service-btn"><Plus size={17}/> Register Service</button></div>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice("")} aria-label="Dismiss notice">×</button></div>}<div className="stat-grid compact-stats"><div className="stat-card"><div className="stat-icon blue"><Box size={21}/></div><div className="stat-copy"><strong>{items.length}</strong><span>Registered components</span></div></div><div className="stat-card"><div className="stat-icon green"><Box size={21}/></div><div className="stat-copy"><strong>{items.filter(i=>i.status==="Registered").length}</strong><span>Registered</span></div></div><div className="stat-card"><div className="stat-icon purple"><Box size={21}/></div><div className="stat-copy"><strong>{items.filter(i=>i.status==="Planned").length}</strong><span>Planned</span></div></div></div><div className="filter-row"><div className="search-field"><Search size={16}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search service, owner or repository..." data-testid="service-search" aria-label="Search services"/></div><span className="muted">{filtered.length} services</span></div><section className="panel"><div className="table-wrap"><table><thead><tr><th>Service</th><th>Type</th><th>Owner</th><th>Repository</th><th>Environment</th><th>Status</th><th>Version</th></tr></thead><tbody>{filtered.map(item=><tr key={item.id} data-testid="catalog-service-row" data-service-id={item.id}><td><div className="entity-cell"><span className="entity-icon"><Box size={18}/></span><div><strong>{item.name}</strong><small>{item.description}</small></div></div></td><td><span className="category-chip">{item.kind}</span></td><td>{item.owner}</td><td><code>{item.repository||"—"}</code></td><td>{item.environment}</td><td><span className={`status-badge ${item.status==="Registered"?"success":"neutral"}`}>{item.status}</span></td><td>{item.version}</td></tr>)}</tbody></table>{!filtered.length&&<div className="empty-state">No services found.</div>}</div></section><div className="info-banner"><Box size={19}/><div><strong>Deployment management is a later phase</strong><p>This catalog currently stores demo metadata. Docker image builds, Kubernetes manifests, permissions and deployment actions will be integrated by the backend/deployment owner.</p></div></div>
 {modal&&<Modal title="Register Deployable Service" onClose={()=>setModal(false)} testId="register-service-modal"><form className="form-stack" onSubmit={save} data-testid="register-service-form"><label>Service name<input required value={name} onChange={e=>setName(e.target.value)} data-testid="catalog-service-name-input"/></label><label>Type<select value={kind} onChange={e=>setKind(e.target.value as CatalogService["kind"])} data-testid="catalog-service-kind-select"><option>Client</option><option>API</option><option>Worker</option><option>MCP</option><option>Data</option></select></label><label>Owner/team<input required value={owner} onChange={e=>setOwner(e.target.value)} data-testid="catalog-service-owner-input"/></label><label>Repository<input value={repository} onChange={e=>setRepository(e.target.value)} placeholder="organization/repository" data-testid="catalog-service-repository-input"/></label><label>Environment<select value={environment} onChange={e=>setEnvironment(e.target.value)} data-testid="catalog-service-environment-select"><option>local</option><option>development</option><option>staging</option><option>production</option></select></label><label>Description<input value={description} onChange={e=>setDescription(e.target.value)} data-testid="catalog-service-description-input"/></label><div className="form-actions"><button type="button" className="button secondary" onClick={()=>setModal(false)}>Cancel</button><button className="button primary" type="submit" data-testid="save-catalog-service-btn">Register</button></div></form></Modal>}</div>;
}
